### PR TITLE
fix: reference to packed field is unaligned

### PR DESCRIPTION
**Pull request by Taowyoo**
The main changes are  in commit: [fix: reference to packed field is unaligned](https://github.com/jethrogb/pe-rs/pull/7/commits/127b9bd57f34b63f8b38ccbaa57fa29d46c30d3e)
The other commit are code refactor to resolve some warning of deprecated macro or syntax.

### CODE REVIEW

**Comment by Taowyoo** [comment]
@jethrogb could you help reivew this PR?

**Review by arai-fortanix — COMMENTED** [review]
This looks like it changes public interfaces, so is this an incompatible change to the crate?

**Comment by Taowyoo** [comment]
> This looks like it changes public interfaces, so is this an incompatible change to the crate?

Yes, you are correct. Since I found the `0.2.0` is not published so I do not bump the version.
Will need some changes in  https://github.com/fortanix/rust-sgx/blob/master/intel-sgx/sgxs-tools/src/bin/isgx-pe2sgx.rs   for incompatible change here

**Comment by arai-fortanix** [comment]
I tried compiling this locally, and it also complained about the use of the `bitflags!` macro in src/types.rs using the deprecated `try!` macro. So the bitflags dependency also may need to be updated. That may require further source changes.

**Comment by arai-fortanix** [comment]
I'm wondering if we can just get rid of `pe2sgxs` though. Does anyone actually use it?

**Comment by Taowyoo** [comment]
> bitflags! macro in src/types.rs using the deprecated try! macro

No problem, it could be resolved by updating `bitflags`

**Comment by Taowyoo** [comment]
> I tried compiling this locally, and it also complained about the use of the `bitflags!` macro in src/types.rs using the deprecated `try!` macro. So the bitflags dependency also may need to be updated. That may require further source changes.

If update `bitflags!`  to new version: >=`1.0.0`, the the new `bitflags` use some refrence in it's macro which cause compile error

**Pull request closed without merging**
