### PR TITLE
Allow retrieving slices of the PE with an FP

### PR DESCRIPTION
**Pull request by aidanhs**
Analogous to `ref_at` and `ref_slice_at` for RVA.

### CODE REVIEW

**Comment by jethrogb** [comment]
Can you also add one for FP<[CChar]>?

**Comment by jethrogb** [comment]
Actually, `FP` is not currently a publicly reachable type, probably intentionally, although I don't remember why...

**Comment by aidanhs** [comment]
`ref_cstr_at(&self, rva: RVA<[CChar]>)` uses section boundaries to limit the cstr. The equivalent for `FP` would probably need to use the end of the file as a boundary. I could do that?

Good catch about it not being public, I've actually exposed it on another branch of mine so I can use it. Bit surprised rustc didn't warn me that I'm exposing a private type, but never mind. I've now modified the PR to expose FP...assuming you have no objections, since you can't remember why it wasn't originally exposed? :)

**Comment by jethrogb** [comment]
`FPRef::ref_cstr_at` already checks for the file boundary, so I think that could just go through without any extra checks.

**Comment by jethrogb** [comment]
Oh you need to pass in a `maxlen`. Can you change the parameter to `FPRef::ref_cstr_at` to an Option<u32> then?

**Comment by aidanhs** [comment]
Made change

**Comment by jethrogb** [comment]
I think this changes the semantics, `maxlen` used to limit `end-start` but now it limits `end`.

**Comment by aidanhs** [comment]
Good catch! Can you take another look? (I'm probably too tired to be writing code if it's wrong again...)

**Comment by jethrogb** [comment]
Looks good (and tests ok), thanks!

**Pull request merged**
